os: linux
dist: xenial
language: python


python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

script:
  - pip install --upgrade --upgrade-strategy eager -e .[dev]
  - py.test -vs --cache-clear
